[project]
name = "sme-toolkit"
version = "0.1.0"
description = "SME: Unified Forensic Workstation for Semantic Memory"
dependencies = [
    "click",
    "colorama",
    "psutil",
    "pandas"
]

[project.scripts]
sme = "sme_cli.main:cli"

[tool.setuptools]
packages = ["sme_cli", "src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
